"""Generate a fixed native API catalog from Cockos' downloaded Lua reference."""
import argparse
import hashlib
import html
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
BLOCKED = {
    "ExecProcess": "External process execution is outside the DAW API transport.",
    "AddRemoveReaScript": "Use the existing Scripts-folder-scoped script_run tool.",
    "ReaScriptError": "May terminate the persistent bridge.",
    "Undo_BeginBlock": "The transport owns undo boundaries.",
    "Undo_EndBlock": "The transport owns undo boundaries.",
    "Undo_BeginBlock2": "The transport owns undo boundaries.",
    "Undo_EndBlock2": "The transport owns undo boundaries.",
    "PreventUIRefresh": "An unbalanced call can freeze the user's interface.",
}


def parse_reference(source):
    entries = {}
    for section in re.split(r'<a name="', source)[1:]:
        name = section.split('"', 1)[0]
        match = re.search(r'<div class="l_func">.*?<code>(.*?)</code>', section, re.S)
        if not match:
            continue
        signature = html.unescape(re.sub(r'<[^>]*>', '', match[1])).strip()
        signature_match = re.search(r'reaper\.(\w+)\((.*)\)', signature)
        if not signature_match or signature_match[1] != name:
            continue
        arguments = []
        for argument in signature_match[2].split(','):
            argument = argument.strip()
            if not argument:
                continue
            # Cockos documents RECT fields as "integerr.left" on some entries.
            argument = re.sub(r'^integerr\.', 'integer r.', argument)
            kind, argname = argument.rsplit(' ', 1)
            optional = kind.startswith('optional ')
            arguments.append({'type': kind.removeprefix('optional ').strip(), 'name': argname, 'optional': optional})
        # Ship interface metadata and a source link, not a copy of Cockos' prose.
        description = 'Native REAPER function ' + name + '. Reference: https://www.reaper.fm/sdk/reascript/reascripthelp.html#' + name
        returns = re.findall(r'<i>(.*?)</i>', match[1].split('reaper.', 1)[0])
        entries[name] = {'name': name, 'signature': signature, 'arguments': arguments, 'returns': returns,
                         'description': description[:16000], 'blocked_reason': BLOCKED.get(name)}
    return entries


def generate(source_path):
    raw = source_path.read_bytes()
    source = raw.decode('utf-8')
    entries = parse_reference(source)
    if len(entries) < 700:
        raise ValueError('Reference parser found fewer than 700 native Lua functions')
    version = re.search(r'Generated by REAPER v([^<]+)', source)[1]
    catalog = {'reaper_version': version, 'source': 'https://www.reaper.fm/sdk/reascript/reascripthelp.html',
               'source_sha256': hashlib.sha256(raw).hexdigest(), 'functions': entries}
    (ROOT / 'reaper_mcp/native_api.json').write_text(json.dumps(catalog, ensure_ascii=True, indent=2) + '\n', encoding='utf-8')
    lines = ['-- BEGIN GENERATED REAPER API CATALOG', 'local native_catalog = {']
    for name, entry in sorted(entries.items()):
        if entry['blocked_reason']:
            continue
        args = ','.join('{kind=' + json.dumps(a['type']) + ',optional=' + str(a['optional']).lower() + '}' for a in entry['arguments'])
        returns = ','.join(json.dumps(t.strip()) for t in entry['returns'])
        lines.append(f'  [{json.dumps(name)}] = {{fn=function(...) return reaper.{name}(...) end, args={{{args}}}, returns={{{returns}}}}},')
    lines.extend(['}', '-- END GENERATED REAPER API CATALOG'])
    target = ROOT / 'reaper_scripts/reaper_mcp_server.lua'
    lua = target.read_text(encoding='utf-8')
    block = '\n'.join(lines)
    if '-- BEGIN GENERATED REAPER API CATALOG' in lua:
        lua = re.sub(r'-- BEGIN GENERATED REAPER API CATALOG.*?-- END GENERATED REAPER API CATALOG', lambda _: block, lua, flags=re.S)
    else:
        lua = lua.replace('local transport = {}', block + '\n\nlocal transport = {}', 1)
    fragment = (ROOT / 'reaper_scripts/native_api_runtime.inc.lua').read_text(encoding='utf-8')
    runtime_start = lua.index('-- This source fragment')
    runtime_end = lua.index('local transport = {}', runtime_start)
    lua = lua[:runtime_start] + fragment + '\n' + lua[runtime_end:]
    target.write_text(lua, encoding='utf-8')
    print(f'Generated {len(entries)} documented functions; {len(entries)-len(BLOCKED)} callable entries')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('reference', type=Path)
    generate(parser.parse_args().reference)
